repos:
  - repo: local
    hooks:
      - id: binaryninja-free
        name: binaryninja-free
        entry: ./build binaryninja-free
        language: system
        files: ^binaryninja-free/PKGBUILD$
        pass_filenames: false

      - id: cargo-afl
        name: cargo-afl
        entry: ./build cargo-afl
        language: system
        files: ^cargo-afl/PKGBUILD$
        pass_filenames: false

      - id: cargo-loc
        name: cargo-loc
        entry: ./build cargo-loc
        language: system
        files: ^cargo-loc/PKGBUILD$
        pass_filenames: false

      - id: chr
        name: chr
        entry: ./build chr
        language: system
        files: ^chr/PKGBUILD$
        pass_filenames: false

      - id: cot
        name: cot
        entry: ./build cot
        language: system
        files: ^cot/PKGBUILD$
        pass_filenames: false

      - id: fernflower-git
        name: fernflower-git
        entry: ./build fernflower-git
        language: system
        files: ^fernflower-git/PKGBUILD$
        pass_filenames: false

      - id: multi-gitter
        name: multi-gitter
        entry: ./build multi-gitter
        language: system
        files: ^multi-gitter/PKGBUILD$
        pass_filenames: false

      - id: rewrk
        name: rewrk
        entry: ./build rewrk
        language: system
        files: ^rewrk/PKGBUILD$
        pass_filenames: false

      - id: topiary
        name: topiary
        entry: ./build topiary
        language: system
        files: ^topiary/PKGBUILD$
        pass_filenames: false

      - id: tundra
        name: tundra
        entry: ./build tundra
        language: system
        files: ^tundra/PKGBUILD$
        pass_filenames: false

      - id: tundra-git
        name: tundra-git
        entry: ./build tundra-git
        language: system
        files: ^tundra-git/PKGBUILD$
        pass_filenames: false
