#!/usr/bin/env bash
set -e

DIR=$1
[ -n "$DIR" ] || {
	>&2 echo "ERROR: Missing required argument"
	exit 2
}
[[ $DIR =~ ^[a-zA-Z0-9/_-]+$ ]] || {
	>&2 echo "ERROR: Invalid input"
	exit 2
}

if command -v makepkg >/dev/null && [ -z "${PKGBUILD_DOCKER:-}" ]; then
	pushd "$DIR" || exit
	# Don't install (-i) since we may not have root permissions and might hang.
	makepkg -sf --noconfirm
else
	docker run \
		--rm \
		-v "$PWD":"/mnt" \
		-w /mnt \
		lahmanja/archlinux:2026-03-01 \
		bash -c "pacman -Sy --noconfirm && chown builder -R ${DIR} && su builder -c 'cd ${DIR} && makepkg -Csi --noconfirm' && chown root -R ${DIR}"
fi
