[binaryninja-free]
source = "github"
github = "Vector35/binaryninja-api"
use_max_tag = true
prefix = "stable/"
include_regex = "^stable/.+$"

[cargo-afl]
source = "github"
github = "rust-fuzz/afl.rs"
use_max_tag = true
prefix = "v"

[cargo-loc]
source = "manual"
manual = "0.1.2"

[chr]
source = "github"
github = "pemistahl/chr"
use_max_tag = true
prefix = "v"

[cot]
source = "github"
github = "cot-rs/cot"
use_max_tag = true
prefix = "cot-cli-v"
include_regex = "^cot-cli-v.+$"

[fernflower-git]
source = "manual"
manual = "261.20362.25.r20.gd426f6e"

[multi-gitter]
source = "github"
github = "lindell/multi-gitter"
use_max_tag = true
prefix = "v"

[rewrk]
source = "github"
github = "lnx-search/rewrk"
use_max_tag = true

[topiary]
source = "github"
github = "topiary/topiary"
use_max_tag = true
prefix = "v"

[tundra]
source = "github"
github = "m4tx/tundra"
use_max_tag = true
prefix = "v"

[tundra-git]
source = "manual"
manual = "0.5.4.r26.gaf90cf7"
